# Site settings
title: Software, technology and experementation
email: nikolay.v.golub@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software development, languages, tools and everything else
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://citizen-stig.github.io" # the base hostname & protocol for your site
twitter_username: citizen_stig
github_username:  citizen-stig

# Build settings
markdown: kramdown
